services:
  postgresql:
    image: postgres:latest
    container_name: fskit_postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PasSw0rd
    ports:
      - "15433:5432"
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge